### PR TITLE
UI Rework (Down with the system decorations!)

### PR DESCRIPTION
**Pull request by roobscoob**

### CODE REVIEW

**Comment by roobscoob** [comment]
probably should have included a preview of what these changes look like:
preview

**Comment by alii** [comment]
image
Noting that non-windows hosts could do with some work

**Comment by roobscoob** [comment]
need to know if linux shifts to the left or right before macos can be fixed.

**Comment by roobscoob** [comment]
I mean I could assume left/right, and that would fix macos leaving linux in a broken state..?

**Review by alii — APPROVED** [review]
lgtm, embedded assets working nicely

**Pull request merged**
