### PR TITLE
feat: access private messages

### PR DESCRIPTION
**Pull request by Bloeckchengrafik**
Hi team!

Here's what I'm currently working on:

(i'll update this image as i progress)

When I get access to the discord guild, I'll also implement the designed tree view. But for now, functionality of the channel switching is more important for me.

If there is any feature that you want/need in this early version of the sidebar, please let me know!

Greetings, 
Christian B.

### CODE REVIEW

**Comment by DovidP** [comment]
Looks good so far! The channel, guild and user caching will be handled in serenity, so try to focus more on the ui side of things. Serenity is not yet working, but I will hopefully have a fix by the end of the week.

**Comment by roobscoob** [comment]
Read over this, It's pretty good and probably for the most part how I would have implemented it if I was forced at gunpoint to make this feature Right Now. However broadly I think it's a little too early to be working on this. We are waiting on changes to Serenity from @Sanae6 and @DovidP (iirc) to handle the Ready packet that you presently have to manually extract data from.

**Comment by Bloeckchengrafik** [comment]
Currently there are two options for me:

I implement the ui part for now and wait until the required serenity changes are done. Then I'll change the data loading and  un-draft the pr.

Or i can start working on another feature.

What do you think is the better option?

**Comment by roobscoob** [comment]
Personally, I would hold off and work on another feature. Almost all UI is non-final and mostly just there to build out the underlying structure as the designers work on their stuff.

I'm focusing mostly on structural chat things for that reason. I'd say reactions are a non-trivial feature that would almost certainly survive a lot of upcoming changes!

**Comment by Bloeckchengrafik** [comment]
I'll close this for now. Will reopen & update when we're there and i have the time to do this :)

**Pull request closed without merging**
