### PR TITLE
Channel History

### PR DESCRIPTION
**Pull request by roobscoob**
This PR implements:
- Message history
- Async Lists
- An async list cache
- An implementation of async list for discord channels
- Async list renderer (specialized for channels, ideally this would be genericized, but I couldn't find a good abstraction for message merging)

Issues with this pr:
- Async list rendering's scroll behaviour is still very weird when messages are added or removed. It's much better than main, but still very imperfect.
- It's probably slow. No perf testing has been done

Atlas

### CODE REVIEW

**Comment by circularsprojects** [comment]
can we try and fix the cargo clippy errors before merge

**Comment by roobscoob** [comment]
Will do

**Comment by roobscoob** [comment]
cargo clippy issues fixed. IMO this is ready to merge.

**Review by bvvst — APPROVED** [review]
:catnoyes:

**Pull request merged**
