### PR TITLE
feat: show message timestamp next to the top message that is grouped

### PR DESCRIPTION
**Pull request by Bloeckchengrafik**
Hello Scope Team,

Awesome project you got here! I'd love to contribute more if my time allows! Also really appreciate the switch to gpui!

This is a rather small PR, I know. But I just wanted to get feedback about project style guides, since there is currently no documentation about this. 

So, if there is anything you don't like in here, feel free to criticize me! It can only help.

Also some small note: Should the last message time or the oldest message time in a group be displayed? The native discord client does first message and shows subsequent message timestamp on hover, the current implementation uses the last message and no hover yet.

Thanks for reading and considering pulling.

Greetings, 
Christian Bergschneider

### CODE REVIEW

**Comment by circularsprojects** [comment]
> Also some small note: Should the last message time or the oldest message time in a group be displayed? The native discord client does first message and shows subsequent message timestamp on hover, the current implementation uses the last message and no hover yet.

I think we should try and match discord as close as possible, and use the first message in a group to display the timestamp.

Also, we have some mockups and stuff in our discord server, https://discord.gg/tWCKbAYF (you have to apply to get in since its a "clan server", but you should get accepted pretty fast)

**Review by roobscoob — APPROVED** [review]
LGTM! Great PR.

NIT: maybe add .editorconfig to gitignore? not sure which editor this is for. We use rustfmt for formatting as a standard.

**Comment by alii** [comment]
This is great, thanks. Re the comment above, will merge this and then remove the .editorconfig

**Review by alii — APPROVED** [review]

**Comment by Bloeckchengrafik** [comment]
The .editorconfig file is a universal configuration for many ides. For example RustRover doesn't use the rustfmt config per default. But there are options to configure it. My bad. Thanks for the info!

Concerning Discord: I applied a few days ago already. I'm just waiting on the request to go through.

Have a wonderful morning/day/evening/night whereever in the world you're coming from!

**Comment by alii** [comment]
No worries, thank you again for the pr. Perhaps we should add some notes in the readme about it, since it's an opt-in setting on RustRover (although it is supported).

My opinion on the .editorconfig file is that not enough tools/languages fully support it, and you can get better formatting with more integrated tools (like rustfmt for Rust, prettier for JavaScript, etc).

Will chase your Discord request as well. Thanks again

**Pull request merged**
