### PR TITLE
stop blocking on serenity::Client::start

### PR DESCRIPTION
**Pull request by Sanae6**
DiscordClient was erroneously awaiting on serenity::Client::start when it shouldn't have been. (my fault!)

### CODE REVIEW

**Review by bvvst — APPROVED** [review]
don't let it happen again.

**Review by DovidP — APPROVED** [review]

**Comment by Sanae6** [comment]
i'm so sorry i will never make a mistake again....

**Review by circularsprojects — APPROVED** [review]

**Comment by okdargy** [comment]
i'm dargy and i approve this commit 👍 (github will now let it go thru)

**Comment by circularsprojects** [comment]
magic merge powers... GO!!!

**Pull request merged**
