### PR TITLE
macOS Code Signing & Local build scripts & Improved Issue template

### PR DESCRIPTION
**Pull request by 0PandaDEV**
I implemented macOS Code Signing as well as 3 build scripts to build Scope locally on the respective devices.

CleanShot 2024-11-18 at 11  29 25

For the Code Singing to work, there needs to be a few environment variables in this repo:
- `APPLE_CERTIFICATE`: Base64 encoded .p12 certificate file
- `APPLE_CERTIFICATE_PASSWORD`: Password for the certificate
- `APPLE_ID`: Apple Developer ID Email
- `APPLE_ID_PASSWORD`: [App-specific password](https://discussions.apple.com/thread/254805086?sortBy=rank) for your Apple ID
- `KEYCHAIN_PASSWORD`: Any secure password for the temporary keychain

### CODE REVIEW

**Comment by circularsprojects** [comment]
if i remember correctly you can submit apps to the notary service without having to use apple id email/password, i'm gonna have a bit of a look at it

**Comment by circularsprojects** [comment]
> if i remember correctly you can submit apps to the notary service without having to use apple id email/password, i'm gonna have a bit of a look at it

i was right, you can make a signing profile with an app store connect api key, and then use that to notarize apps
image
you can then just use `xcrun notarytool submit [path] --keychain-profile [profile]`

not entirely sure how to do this via github actions though

**Comment by 0PandaDEV** [comment]
Ok, but this requires a Paid Developer account, which I don't have, so I can't test this.

**Comment by circularsprojects** [comment]
> Ok, but this requires a Paid Developer account, which I don't have, so I can't test this.

i can test it out in my fork

also doesn't using the notary service at all require a paid dev account?

**Comment by 0PandaDEV** [comment]
No you can sign with a free account it will just pop up as unverified but at least it's no longer damaged.
CleanShot 2024-11-18 at 12  38 10

**Comment by circularsprojects** [comment]
> No you can sign with a free account it will just pop up as unverified but at least it's no longer damaged. CleanShot 2024-11-18 at 12  38 10

ohhh right

**Review by circularsprojects — APPROVED** [review]

**Review by alii — CHANGES_REQUESTED** [review]
Needs `APP_BUNDLE_ID` to be loaded in actual workflow file. Can hardcode it in the yml file under `env:` _i think_

**Comment by 0PandaDEV** [comment]
so what should the that be?

com.scopeclient.scope ?

**Comment by alii** [comment]
com.scopeclient.desktop imo

**Review by alii — APPROVED** [review]

**Pull request merged**
